// <auto-generated />
using System;
using AVWebsite.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AVWebsite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220217105744_TourCate_TourType")]
    partial class TourCate_TourType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.14");

            modelBuilder.Entity("AVWebsite.Models.About", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Abouts");
                });

            modelBuilder.Entity("AVWebsite.Models.AdditionalService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FeatureImage")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("AdditionalServices");
                });

            modelBuilder.Entity("AVWebsite.Models.BookingStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BookingStatuses");
                });

            modelBuilder.Entity("AVWebsite.Models.Gallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Galleries");
                });

            modelBuilder.Entity("AVWebsite.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FeatureImage")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("AVWebsite.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<float>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("AVWebsite.Models.Tour.About_Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AboutId")
                        .HasColumnType("int");

                    b.Property<int>("ToursId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AboutId");

                    b.HasIndex("ToursId");

                    b.ToTable("About_Tours");
                });

            modelBuilder.Entity("AVWebsite.Models.Tour.AdditionalService_Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AdditionalServiceId")
                        .HasColumnType("int");

                    b.Property<int>("ToursId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdditionalServiceId");

                    b.HasIndex("ToursId");

                    b.ToTable("AdditionalService_Tours");
                });

            modelBuilder.Entity("AVWebsite.Models.Tour.Location_Tours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("ToursId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ToursId");

                    b.ToTable("Location_Tours");
                });

            modelBuilder.Entity("AVWebsite.Models.Tour.Review_Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.Property<int>("ToursId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.HasIndex("ToursId");

                    b.ToTable("Review_Tours");
                });

            modelBuilder.Entity("AVWebsite.Models.Tour.TourCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TourCategories");
                });

            modelBuilder.Entity("AVWebsite.Models.Tour.TourCategory_Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("TourCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("ToursId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourCategoryId");

                    b.HasIndex("ToursId");

                    b.ToTable("TourCategory_Tours");
                });

            modelBuilder.Entity("AVWebsite.Models.Tour.TourFaq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TourFaqs");
                });

            modelBuilder.Entity("AVWebsite.Models.Tour.TourFaq_Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("TourFaqId")
                        .HasColumnType("int");

                    b.Property<int>("ToursId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourFaqId");

                    b.HasIndex("ToursId");

                    b.ToTable("TourFaq_Tours");
                });

            modelBuilder.Entity("AVWebsite.Models.Tour.TourPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Exclusion")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Inclusion")
                        .HasColumnType("text");

                    b.Property<int>("MaximumPersion")
                        .HasColumnType("int");

                    b.Property<int>("MinimumPerson")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("UnitName")
                        .HasColumnType("text");

                    b.Property<float>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TourPackages");
                });

            modelBuilder.Entity("AVWebsite.Models.Tour.TourPackage_Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("TourPackageId")
                        .HasColumnType("int");

                    b.Property<int>("ToursId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourPackageId");

                    b.HasIndex("ToursId");

                    b.ToTable("TourPackage_Tours");
                });

            modelBuilder.Entity("AVWebsite.Models.Tour.TourType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TourTypes");
                });

            modelBuilder.Entity("AVWebsite.Models.Tour.Tours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("AverageRating")
                        .HasColumnType("float");

                    b.Property<string>("Duration")
                        .HasColumnType("text");

                    b.Property<string>("Exclusion")
                        .HasColumnType("text");

                    b.Property<string>("FeatureImage")
                        .HasColumnType("text");

                    b.Property<int>("FeaturePrice")
                        .HasColumnType("int");

                    b.Property<string>("FeaturePriceText")
                        .HasColumnType("text");

                    b.Property<string>("FullDescription")
                        .HasColumnType("text");

                    b.Property<int>("GalleryId")
                        .HasColumnType("int");

                    b.Property<string>("Highlightis")
                        .HasColumnType("text");

                    b.Property<string>("Inclusions")
                        .HasColumnType("text");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<float>("MapLat")
                        .HasColumnType("float");

                    b.Property<float>("MapLong")
                        .HasColumnType("float");

                    b.Property<int>("MaximumPerson")
                        .HasColumnType("int");

                    b.Property<int>("MinimumPersion")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("TourCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("TourTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GalleryId");

                    b.HasIndex("LocationId");

                    b.HasIndex("TourCategoryId");

                    b.HasIndex("TourTypeId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("AVWebsite.Models.Tour.WhatToExpect_Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ToursId")
                        .HasColumnType("int");

                    b.Property<int>("WhatToExpectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToursId");

                    b.HasIndex("WhatToExpectId");

                    b.ToTable("WhatToExpect_Tours");
                });

            modelBuilder.Entity("AVWebsite.Models.TourType_Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("TourTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ToursId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourTypeId");

                    b.HasIndex("ToursId");

                    b.ToTable("TourType_Tours");
                });

            modelBuilder.Entity("AVWebsite.Models.WhatToExpect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WhatToExpects");
                });

            modelBuilder.Entity("AVWebsite.Models.Tour.About_Tour", b =>
                {
                    b.HasOne("AVWebsite.Models.About", "About")
                        .WithMany()
                        .HasForeignKey("AboutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVWebsite.Models.Tour.Tours", "Tours")
                        .WithMany()
                        .HasForeignKey("ToursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("About");

                    b.Navigation("Tours");
                });

            modelBuilder.Entity("AVWebsite.Models.Tour.AdditionalService_Tour", b =>
                {
                    b.HasOne("AVWebsite.Models.AdditionalService", "AdditionalService")
                        .WithMany()
                        .HasForeignKey("AdditionalServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVWebsite.Models.Tour.Tours", "Tours")
                        .WithMany()
                        .HasForeignKey("ToursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdditionalService");

                    b.Navigation("Tours");
                });

            modelBuilder.Entity("AVWebsite.Models.Tour.Location_Tours", b =>
                {
                    b.HasOne("AVWebsite.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVWebsite.Models.Tour.Tours", "Tours")
                        .WithMany()
                        .HasForeignKey("ToursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Tours");
                });

            modelBuilder.Entity("AVWebsite.Models.Tour.Review_Tour", b =>
                {
                    b.HasOne("AVWebsite.Models.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVWebsite.Models.Tour.Tours", "Tours")
                        .WithMany()
                        .HasForeignKey("ToursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("Tours");
                });

            modelBuilder.Entity("AVWebsite.Models.Tour.TourCategory_Tour", b =>
                {
                    b.HasOne("AVWebsite.Models.Tour.TourCategory", "TourCategory")
                        .WithMany()
                        .HasForeignKey("TourCategoryId");

                    b.HasOne("AVWebsite.Models.Tour.Tours", "Tours")
                        .WithMany()
                        .HasForeignKey("ToursId");

                    b.Navigation("TourCategory");

                    b.Navigation("Tours");
                });

            modelBuilder.Entity("AVWebsite.Models.Tour.TourFaq_Tour", b =>
                {
                    b.HasOne("AVWebsite.Models.Tour.TourFaq", "TourFaq")
                        .WithMany()
                        .HasForeignKey("TourFaqId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVWebsite.Models.Tour.Tours", "Tours")
                        .WithMany()
                        .HasForeignKey("ToursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TourFaq");

                    b.Navigation("Tours");
                });

            modelBuilder.Entity("AVWebsite.Models.Tour.TourPackage_Tour", b =>
                {
                    b.HasOne("AVWebsite.Models.Tour.TourPackage", "TourPackage")
                        .WithMany()
                        .HasForeignKey("TourPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVWebsite.Models.Tour.Tours", "Tours")
                        .WithMany()
                        .HasForeignKey("ToursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TourPackage");

                    b.Navigation("Tours");
                });

            modelBuilder.Entity("AVWebsite.Models.Tour.Tours", b =>
                {
                    b.HasOne("AVWebsite.Models.Gallery", "Gallery")
                        .WithMany()
                        .HasForeignKey("GalleryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVWebsite.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVWebsite.Models.Tour.TourCategory", "TourCategory")
                        .WithMany()
                        .HasForeignKey("TourCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVWebsite.Models.Tour.TourType", "TourType")
                        .WithMany()
                        .HasForeignKey("TourTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gallery");

                    b.Navigation("Location");

                    b.Navigation("TourCategory");

                    b.Navigation("TourType");
                });

            modelBuilder.Entity("AVWebsite.Models.Tour.WhatToExpect_Tour", b =>
                {
                    b.HasOne("AVWebsite.Models.Tour.Tours", "Tours")
                        .WithMany()
                        .HasForeignKey("ToursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVWebsite.Models.WhatToExpect", "WhatToExpect")
                        .WithMany()
                        .HasForeignKey("WhatToExpectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tours");

                    b.Navigation("WhatToExpect");
                });

            modelBuilder.Entity("AVWebsite.Models.TourType_Tour", b =>
                {
                    b.HasOne("AVWebsite.Models.Tour.TourType", "TourType")
                        .WithMany()
                        .HasForeignKey("TourTypeId");

                    b.HasOne("AVWebsite.Models.Tour.Tours", "Tours")
                        .WithMany()
                        .HasForeignKey("ToursId");

                    b.Navigation("Tours");

                    b.Navigation("TourType");
                });
#pragma warning restore 612, 618
        }
    }
}
